version: "3.7"

services:
    tsbot:
        container_name: tsbot
        image: tsbot:latest
        volumes:
            - ./service-account.json:/app/service-account.json
            - ./bot_token.py:/app/bot_token.py
            - ./resources:/app/resources
